# see: https://github.com/pages-themes/cayman
theme: jekyll-theme-cayman
repository: chirimen-oh/tutorials
title: '<a href="/" style="color: white">CHIRIMEN チュートリアル</a>'
description: >-
  <a href="https://chirimen.org/" style="color: white">CHIRIMEN</a> for Raspberry Pi 3
  を初めて使う方向けの <a href="/raspi3/ja/" style="color: white">チュートリアル集</a> です<br>
  <a href="/raspi3/ja/" style="color: white">目次のページ</a> からチュートリアルの各ページをご覧ください<br>
  Enjoy <a href="/raspi3/en/" style="color: white">Tutorials for CHIRIMEN for Raspberry Pi 3</a>
show_downloads: false
# google_analytics:
include: _redirects

# Use CommonMarkGhPages for Markdown parser
# https://github.com/github/jekyll-commonmark-ghpages
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Use Kramdown for Markdown parser (obsolete)
# https://help.github.com/articles/configuring-jekyll/
# markdown: kramdown
# kramdown:
#   input: GFM
#   hard_wrap: false
#   math_engine: mathjax
#   syntax_highlighter: rouge
# gfm_quirks: paragraph_end
